version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - unused
  disable:
    - errcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST*"
        - "-QF*"
        - "-SA9003"
        - "-SA9004"
        - "-SA4024"

run:
  timeout: 4m
